language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
  - node_modules
  - "$(npm config get prefix)/node_modules"
before_install: npm install
script:
- npm run build
- npm run test-ci
- npm run docs
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | coveralls -v
jobs:
  include:
  - stage: npm release
    node_js: '10'
    script: npm run build
    if: tag IS present
    deploy:
      provider: npm
      skip_cleanup: true
      email: $npm_email
      api_key: $npm_api_key
      on:
        tags: true
        repo: donmahallem/FlowApiTypes
  - stage: github pages release
    node_js: '10'
    script: npm run docs
    if: branch = master
    deploy:
      provider: pages
      skip-cleanup: true
      local-dir: docs
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master