name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v1 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Github Automatic Npm Release Action
        uses: donmahallem/github-release-action@v1.0.0
        env:
          github_secret: ${{ secrets.GITHUB_TOKEN }}
